set_property SRC_FILE_INFO {cfile:C:/Users/sarun/Downloads/Cora-Z7-07S-Master.xdc rfile:../../../../../../Downloads/Cora-Z7-07S-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3107 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to 
set_property src_info {type:XDC file:1 line:3108 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports clk]
set_property src_info {type:XDC file:1 line:3109 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports rst]
set_property src_info {type:XDC file:1 line:6273 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to 
set_property src_info {type:XDC file:1 line:6275 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports clk] -to [get_pins {u_ila_0/inst/ila_core_inst/shifted_data_in_reg[7][65]_srl8/D}]
set_property src_info {type:XDC file:1 line:6276 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports clk] -to [get_pins {u_ila_0/inst/ila_core_inst/shifted_data_in_reg[7][65]_srl8/D}]
set_property src_info {type:XDC file:1 line:6277 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports clk] -to [get_pins {u_ila_0/inst/ila_core_inst/shifted_data_in_reg[7][65]_srl8/D}]
set_property src_info {type:XDC file:1 line:6279 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:6280 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6281 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6282 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6283 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6284 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6285 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6286 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6287 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6288 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:6289 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:6290 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:6291 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:6292 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {outPC[0]} {outPC[1]} {outPC[2]} {outPC[3]} {outPC[4]} {outPC[5]} {outPC[6]} {outPC[7]} {outPC[8]} {outPC[9]} {outPC[10]} {outPC[11]} {outPC[12]} {outPC[13]} {outPC[14]} {outPC[15]} {outPC[16]} {outPC[17]} {outPC[18]} {outPC[19]} {outPC[20]} {outPC[21]} {outPC[22]} {outPC[23]} {outPC[24]} {outPC[25]} {outPC[26]} {outPC[27]} {outPC[28]} {outPC[29]} {outPC[30]} {outPC[31]}]]
set_property src_info {type:XDC file:1 line:6293 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:6294 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:6295 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:6296 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {ALUoutput[0]} {ALUoutput[1]} {ALUoutput[2]} {ALUoutput[3]} {ALUoutput[4]} {ALUoutput[5]} {ALUoutput[6]} {ALUoutput[7]} {ALUoutput[8]} {ALUoutput[9]} {ALUoutput[10]} {ALUoutput[11]} {ALUoutput[12]} {ALUoutput[13]} {ALUoutput[14]} {ALUoutput[15]} {ALUoutput[16]} {ALUoutput[17]} {ALUoutput[18]} {ALUoutput[19]} {ALUoutput[20]} {ALUoutput[21]} {ALUoutput[22]} {ALUoutput[23]} {ALUoutput[24]} {ALUoutput[25]} {ALUoutput[26]} {ALUoutput[27]} {ALUoutput[28]} {ALUoutput[29]} {ALUoutput[30]} {ALUoutput[31]}]]
set_property src_info {type:XDC file:1 line:6297 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:6298 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:6299 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:6300 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list rst_IBUF]]
set_property src_info {type:XDC file:1 line:6301 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:6302 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:6303 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:6304 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list clk_IBUF]]
set_property src_info {type:XDC file:1 line:6305 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:6306 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:6307 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:6308 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
